### ISSUE TITLE
KosarajuAlgorithm

### ISSUE THREAD

**Issue by StavrWalker** [caxapexac/StronglyConnectedComponentsPractice#10]
Использовал еще не реализованную логику графа. **Нужно состыковать класс KosarajuAlgorithm и класс Graph.** 
Нода должна хранить boolean visited, как минимум для анимации. Для алгоритма также должна быть возможность проверить, что нода находится в компоненте. Это удобно сделать в классе Node, но логичнее вынести это в класс алгоритма как-нибудь.

**Comment by caxapexac** [comment]
LGTM
